server:
  port: 8003
spring:
  application:
    name: spring-cloud-seata-storage
  datasource:
    url: jdbc:mysql://localhost:3306/seata
    username: root
    password: mysqlAdmin
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
#使用mybatis时使用该配置
#mybatis:
#  mapper-locations:
#    - classpath:mybatis/mapper/**/*.xml
#  config-location: classpath:mybatis/mybatis.cfg.xml

#引mybatis-plus使用该配置
mybatis-plus:
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
logging:
  level:
    com.lzj.mapper: debug
seata:
  registry:
    eureka:
    service-url: http://${eureka.instance.hostname}:8761/eureka/
    type: eureka
  enabled: true
  #事务分组名称
  tx-service-group: my_test_tx_group
  service:
    vgroupMapping:
      #事务分组名称对应seata-server在服务注册中心的服务名
      my_test_tx_group: SEATA-SERVER
  client:
    rm:
      lock:
        retry-interval: 30
        retry-times: 10
    tm:
      commit-retry-count: 3 #一阶段全局提交结果上报TC重试次数，默认1次
      rollback-retry-count: 3 #一阶段全局回滚结果上报TC重试次数，默认1次
  application-id: spring-cloud-seata-storage